# Copyright (c) 2025-2026 Mark Buckwell, Zensical and contributors
# SPDX-License-Identifier: MIT
# All contributions are certified under the DCO

pages:
  stage: deploy
  image: python:latest
  tags:
    - pages
  script:
    - apt-get update
    - apt-get install -y pandoc weasyprint
    - pip install -r requirements.txt
    - python build_pdf.py
    - zensical build --clean 
  pages:
    publish: public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'