pages:
  stage: deploy
  image: python:latest
  tags:
    - pages
  script:
    - pip install zensical
    - zensical build --clean -d public
  pages:
    publish: public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'