# Copyright (c) 2025-2026 Mark Buckwell and contributors
# SPDX-License-Identifier: MIT

StylesPath = styles
MinAlertLevel = suggestion
Packages = Microsoft, proselint

# This is the file types that Vale will check. You can add or remove file types as needed.
[*.{md,rst,asciidoc,html}]
BasedOnStyles = Vale, Microsoft, proselint

Vale.Terms = YES
Vale.Avoid = YES
Vale.Spelling = YES

Microsoft.OxfordComma = YES
Microsoft.Passive = YES
Microsoft.Dashes = YES
Microsoft.Spacing = YES
Microsoft.Wordiness = YES
Microsoft.We = YES
